### ISSUE TITLE
pip install stix command is throwing exception

### ISSUE THREAD

**Issue by priyamalik** [csirtgadgets/p5-cif-sdk-stix#3]
First I installed p5-cif-sdk and then run below command

1. sudo apt-get install -y libxml-dev libxslt1-dev cython python-dev python-pip

In this command it is showing error that "not able to locate libxml-dev".
I was trying to install libxml-dev but not able to locate then I installed libxml2-dev and also make changes in the command too:
1. sudo apt-get install -y **libxml2-dev** libxslt1-dev cython python-dev python-pip
After this, this command working fine.

But while running second command
2. pip install stix
It is giving below exception messages:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/stix'

Storing debug log for failure in /home/soc/.pip/pip.log

Please help.

Thanks and Regards,
Priya Malik

**Comment by wesyoung** [comment]
hi!

thanks for the update, sounds like you need to do:

```
$ sudo pip install stix
```

**Comment by priyamalik** [comment]
Hi wesyoung,

Thank you so much. I was doing this silly mistake.
It is working now.

Thanks and Regards,
Priya

**Comment by wesyoung** [comment]
no worries. things can get blurry after a while :)
